
CREATE TABLE CLIENTES(
    ID_CLIENTES INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    FECHA_NACIMIENTO DATE
);
-- LUEGO AÑADIREMOS COLUMNA BANCO


-- CREAR TABLA BANCO

CREATE TABLE BANCOS (
    ID_BANCO INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);


CREATE TABLE CUENTAS_BANCARIAS (
    ID_CUENTA INTEGER PRIMARY KEY,
    IBAN VARCHAR(25) NOT NULL UNIQUE,
    SALDO  DOUBLE DEFAULT 0,
    ID_CLIENTE INTEGER, 
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

-- BORRAR
DROP TABLE XXX;

-- UN CLIENTE PERTENECE A UN SOLO BANCO

ALTER TABLE CLIENTES 
ADD COLUMN ID_BANCO INTEGER ;

ALTER TABLE CLIENTES
ADD FOREIGN KEY (ID_BANCO) REFERENCES  BANCOS(ID_BANCO);


-- INSERT 

-- Bancos
INSERT INTO BANCOS VALUES (1,'Banco ZK');

SELECT * FROM BANCOS;

-- Clientes

INSERT INTO CLIENTES
VALUES (2, 'Antonio','Robles',CURRENT_DATE,1);

INSERT INTO CLIENTES(ID_CLIENTE, NOMBRE, APELLIDOS, ID_BANCO)
VALUES (3, 'Mario','Cortina',1);


select * from clientes;


-- MODIFICAR laura id 1 para que tenga el banco 1
UPDATE CLIENTES
SET ID_BANCO = 1
WHERE ID_CLIENTE = 1;


-- BORRADO

DELETE FROM CLIENTES
WHERE ID_CLIENTE = 3;



-- CUENTA BANCARIA
--1  ES7438844444  14000  1
--2  ES5666777777   500   1
-- 3  ES89E98T9898  4560   2


INSERT INTO CUENTAS_BANCARIAS 
(ID_CUENTA, IBAN, SALDO, ID_CLIENTE) 
VALUES (1, 'ES7438844444', 14000.0, 1);

INSERT INTO CUENTAS_BANCARIAS 
(ID_CUENTA, IBAN, SALDO, ID_CLIENTE) 
VALUES (2, 'ES56777777', 500.0, 1);

INSERT INTO CUENTAS_BANCARIAS 
(ID_CUENTA, IBAN, SALDO, ID_CLIENTE) 
VALUES (3, 'ES89E98T9898', 4560.0, 2);

select * from cuentas_bancarias;

--delete  from cuentas_bancarias;

select cb.ID_CUENTA, cb.IBAN, cb.SALDO, c.NOMBRE, c.APELLIDOS
from cuentas_bancarias cb , clientes c
where cb.ID_CLIENTE = c.ID_CLIENTE;